# API Key
GEMINI_KEY_1 = "" 
GEMINI_KEY_2 = ""
GEMINI_KEY_3 = ""
GEMINI_KEY_4 = "" 
GEMINI_KEY_5 = ""
GEMINI_KEY_6 = ""
GEMINI_KEY_7 = ""
GEMINI_KEY_8 = ""
GEMINI_KEY_9 = ""
GEMINI_KEY_10 = "" 
GEMINI_KEY_11 = ""
GEMINI_KEY_12 = ""
GEMINI_KEY_13 = ""
GEMINI_KEY_14 = ""

# Model Name
MODEL_NAME = "gemini-2.5-flash"
